### ISSUE TITLE
image name and tag seem to vanish

### ISSUE THREAD

**Issue by kelson42** [offspot/docker-export#7]
Once I have exported a Docker image from a repository to a tarball, then I tried to import them with `docker import`.

It seems the images are imported, but tagging and naming have vanished:
```
$ docker images
REPOSITORY                            TAG                IMAGE ID       CREATED              SIZE
<none>                                <none>             4055866b7589   About a minute ago   69.4MB
<none>                                <none>             de5bee81a7a4   2 hours ago          458MB
<none>                                <none>             ad9cf59ba1f9   6 hours ago          2.07GB
```

**Comment by kelson42** [comment]
@rgaudin It seems the core of the problem is that I used `docker import` and I should use `docker load`. Right?!

**Comment by rgaudin** [comment]
Yes this is not what it is intended for.
